### ISSUE TITLE
Extra padding at bottom

### ISSUE THREAD

**Issue by leo-mck** [1iveowl/plugin.label.markdown#12]
Hi, thank you for this, it is the best markdown control I found for XF. I want to use it to replace some labels on my app but right now it seems there is a bottom padding, seem my image below showing a default `Label` and a `LabelMd` inside a StackLayout:

![image](https://user-images.githubusercontent.com/876986/65081900-09323180-d97b-11e9-9e97-355ae3d22243.png)

Is there a way to remove this space so `LabelMd` behaves like a normal `Label`?

**Comment by 1iveowl** [comment]
Thank you 👍 

Good catch. Looks like a bug. 

You can try and set `IsParagraphSpacing="false"`, but actually, I think it is because the code added an additional `New Line` to the end, which it should not. 

I will have a look at it.

**Comment by 1iveowl** [comment]
Fixed in release 1.0.5

**Comment by 1iveowl** [comment]
Fixed in release 1.0.5

**Comment by leo-mck** [comment]
It worked, thank you, amazing work!
