### ISSUE TITLE
Value is an invalid value for TextMarkdown when binding

### ISSUE THREAD

**Issue by leo-mck** [1iveowl/plugin.label.markdown#13]
I have a simple string property `Text` on my VM and try to bind it to `TextMarkdown` like this:

```<markDown:LabelMd TextMarkdown="{Binding Text}" BackgroundColor="Silver"/>```

but this cause the error ```Value is an invalid value for TextMarkdown``` - is this a bug or have I missed something?

**Comment by 1iveowl** [comment]
The XAML look good. 

Is `Text` a Bindable Property? 

Maybe Text starts out as beeing `null`, which triggers the Exception? Now that I think about it, this might be a bug, as null should be acceptable.

**Comment by 1iveowl** [comment]
Fixed in release 1.0.5.

**Comment by 1iveowl** [comment]
Fixed in release 1.0.5

**Comment by 1iveowl** [comment]
The NuGet was a little delayed. It has been published now. Should be available in 5-15 minutes...
